# Generated by Django 4.2.29 on 2026-03-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('phone_raw', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address_input', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('formatted_address', models.TextField(blank=True)),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('reference', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('geocode_source', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('formatted_address', models.TextField(blank=True)),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('reference', models.TextField(blank=True)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('payment', models.CharField(blank=True, max_length=100)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('time_start', models.CharField(blank=True, max_length=10)),
                ('time_end', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('stock_items', models.JSONField(blank=True, default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='OptRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'opt_routes',
                'unique_together': {('date', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver', models.CharField(max_length=100)),
                ('initial', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_stock',
                'unique_together': {('date', 'driver')},
            },
        ),
    ]
